

FAIL event.intercept() throws if used on a canceled event assert_throws_dom: function "() => e.intercept()" did not throw

