

FAIL history.back() does not fire a navigate event when there's nothing to navigate assert_equals: expected 2 but got 0

